### ISSUE TITLE
Reference to undeclared resource

### ISSUE THREAD

**Issue by yum-dev** [bradford-hamilton/terraform-ecs-fargate#10]
Getting ```Reference to undeclared resource``` error. 

Please check below:
```
$ terraform plan

Error: Reference to undeclared resource

  on ecs.tf line 19, in resource "aws_ecs_task_definition" "app":
  19:   execution_role_arn       = aws_iam_role.ecs_task_execution_role.arn

A managed resource "aws_iam_role" "ecs_task_execution_role" has not been
declared in the root module.


Error: Reference to undeclared resource

  on outputs.tf line 2, in output "alb_hostname":
   2:   value = aws_alb.main.dns_name

A managed resource "aws_alb" "main" has not been declared in the root module.
```

**Comment by bradford-hamilton** [comment]
@yum-dev sorry you are having some issues - I can't seem to reproduce the error you're seeing when running `terraform plan`. Without more info, it's hard for me to say what you're running into. `"aws_iam_role" "ecs_task_execution_role"` and `"aws_alb" "main"` are both declared. Maybe for a sanity check try making sure your terraform version is correct, and do a fresh clone of the repo and see what you get.

**Comment by yum-dev** [comment]
@bradford-hamilton  I was following your blog but nothing about ```roles.tf``` has been mentioned there, hence got the error. When I cloned the project, I was able to spot the difference.

**Comment by bradford-hamilton** [comment]
@yum-dev ah gotcha! Sorry, so initially in Part 1 of the blog we created those manually through the AWS GUI, and then Part 2 didn't include roles.tf... Recently I added the roles.tf file so that everything could be created programmatically through Terraform. I added an update message at the top of Part 2 that might help clarify that. Thanks!
