### ISSUE TITLE
Use docker bind mount

### ISSUE THREAD

**Issue by justinush** [bradford-hamilton/terraform-ecs-fargate#11]
I want to deploy https://github.com/sameersbn/docker-gitlab on my ECS. They use docker-compose script to build multiple docker services, and use docker volume. Now, if I use ECS with Fargate launch type, how to adjust this docker-compose script to it?

**Comment by borgified** [comment]
you probably wouldn't use Fargate for that. when you choose to use ECS, you take the configuration specified in your docker-compose.yml to populate your task definition. (eg. your docker volume maps to volumes.)

docker-compose isn't designed to control Fargate

**Comment by justinush** [comment]
Hey thank you for explanation. So, I should use ec2 launch type instead for this?

**Comment by bradford-hamilton** [comment]
Hey @justinushermawan, my gut tells me that @borgified is probably right here and you may want to go with the EC2 launch type... Although after looking into it, it looks like docker-compose can be used with Fargate (ex: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cli-tutorial-fargate.html) but I haven't ever tried it. On the same token Fargate only supports non-persistent storage volumes so I would imagine for your situation it still wouldn't be a viable option.
