### ISSUE TITLE
idempotency issue with role in aws_appautoscaling_target

### ISSUE THREAD

**Issue by borgified** [bradford-hamilton/terraform-ecs-fargate#13]
A "terraform apply" attaches a custom role to the service BUT
AWS will replace the custom role with a service-linked role (AWSServiceRoleForApplicationAutoScaling_ECSService).

This will keep happening every time "terraform apply" is executed.

see: https://forums.aws.amazon.com/thread.jspa?threadID=270113

**Comment by bradford-hamilton** [comment]
Thanks @borgified! Just looked at your PR and will be merging momentarily.
