### ISSUE TITLE
Why are these ports also hardcoded? Surely you can parameterise them?

### ISSUE THREAD

**Issue by christhomas** [bradford-hamilton/terraform-ecs-fargate#2]
https://github.com/bradford-hamilton/terraform-ecs-fargate/blob/776be1af6ad9a3ee960acd8606fd27af0912aa71/terraform/security.tf#L9

**Comment by bradford-hamilton** [comment]
Hey Chris, sorry it took me so long to see this! You are absolutely correct I missed a couple of places where port was hardcoded. Someone made a PR for it and it is now updated.
