### ISSUE TITLE
Suggest to Create Role by Terraform, Got: ClientException: Role is not valid

### ISSUE THREAD

**Issue by geekeren** [bradford-hamilton/terraform-ecs-fargate#8]
I got the error below when run your code
```
Error: ClientException: Role is not valid
	status code: 400, request id: dd60557f-6d91-4c15-8ab9-6d71b20f4609
  on ecs.tf line 19, in resource "aws_ecs_task_definition" "app":
  19: resource "aws_ecs_task_definition" "app" {
```
I suspect it because you hardcoded the aws_ecs_task_definition Role, I suggest to creat thr Role by terraform.

**Comment by bradford-hamilton** [comment]
Hey @geekeren, originally this was part of a 2-part tutorial where the role was made manually in the AWS GUI in step one. Someone has made a PR with the role built out in terraform and I will be adding it soon! Thanks!!

**Comment by geekeren** [comment]
@bradford-hamilton Got it. Thank you.

**Comment by bradford-hamilton** [comment]
Creation of role in terraform was merged in from the other person's PR 👍
