### ISSUE TITLE
Repo is missing a license.

### ISSUE THREAD

**Issue by maraca** [bradford-hamilton/terraform-ecs-fargate#9]
Hi! Thanks a lot for putting this together and for writing an awesome blog post about it.
I noticed that your repo doesn't have a LICENSE file, meaning others may not be able to reuse the code.

Would you consider adding an MIT License file to it? https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by bradford-hamilton** [comment]
Hey @maraca thanks for reaching out! Added MIT license.
